// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockSimulation.EfCore;

#nullable disable

namespace StockSimulation.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("StockSimulation.Domain.Companies.Company", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeSymbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol", "ExchangeSymbol");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("StockSimulation.Domain.Prices.StockPrice", b =>
                {
                    b.Property<string>("StockSymbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeSymbol")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyExchangeSymbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanySymbol")
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("StockSymbol", "ExchangeSymbol", "Date");

                    b.HasIndex("CompanySymbol", "CompanyExchangeSymbol");

                    b.ToTable("StockPrice");
                });

            modelBuilder.Entity("StockSimulation.Domain.Prices.StockPrice", b =>
                {
                    b.HasOne("StockSimulation.Domain.Companies.Company", null)
                        .WithMany("StockPrices")
                        .HasForeignKey("CompanySymbol", "CompanyExchangeSymbol");
                });

            modelBuilder.Entity("StockSimulation.Domain.Companies.Company", b =>
                {
                    b.Navigation("StockPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
